// <auto-generated />
using System;
using CreditManagementSystem.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CreditManagementSystem.Data.EntityFramework.Migrations
{
    [DbContext(typeof(CreditManagementSystemDbContext.CreditManagementSystemReadWriteDbContext))]
    [Migration("20200921204206_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CreditManagementSystem.Data.Model.Credit", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<string>("ClientID")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDay")
                        .HasColumnType("datetime");

                    b.Property<int>("CreditStatusID")
                        .HasColumnType("int");

                    b.Property<double>("DebtPaid")
                        .HasColumnType("double");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ModificationDay")
                        .HasColumnType("datetime");

                    b.HasKey("ID");

                    b.HasIndex("CreditStatusID");

                    b.ToTable("Credit");
                });

            modelBuilder.Entity("CreditManagementSystem.Data.Model.CreditStatus", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("CreditStatus");
                });

            modelBuilder.Entity("CreditManagementSystem.Data.Model.Credit", b =>
                {
                    b.HasOne("CreditManagementSystem.Data.Model.CreditStatus", "CreditStatus")
                        .WithMany()
                        .HasForeignKey("CreditStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
